### ISSUE TITLE
Error on Raspberrian

### ISSUE THREAD

**Issue by thekip** [yortus/asyncawait#23] opened 2015-08-14 14:33 UTC
Error occurs when trying to use await/async functions. 

Here is full stacktrace returned by node

http://pastebin.com/4DAMxaTW

**Comment by yortus** [comment] 2015-08-14 14:46
I see the stack trace, but I can't see the actual exception message in there. What is the text of the error message? And can you show the part of your source code where the error is occurring?

**Comment by thekip** [comment] 2015-08-14 15:07
Yeah, this is a problem. No error text. 

I run script like this 
![image](https://cloud.githubusercontent.com/assets/1586852/9276789/b34a3388-42ae-11e5-9357-eb0ea90fe9bf.png)

And all content from `debug.log` i pasted to pastebin. 

Also my script contains: 
```js
var async = require('asyncawait/async');
var await = require('asyncawait/await');

async(function(){})
```

**Comment by yortus** [comment] 2015-08-15 08:43
Looking at the stack trace, it seems to be failing at startup trying to load bluebird, on the line:
```javascript
var Promise = require('bluebird');
```
Can you try running that line on its own in your source file? Does it work?

**Comment by thekip** [comment] 2015-08-17 08:05
I've added `bluebird` into packages.json, and then add `require` on top of my script. 
Script start and finish correctly.

**Comment by yortus** [comment] 2015-08-17 08:24
OK. There is something strange about the stack trace. The error appears to come from `bluebird` as per line 1 of the stack trace. That line indicates the error occurs in the file `/home/pi/smarthome/node_modules/asyncawait/node_modules/bluebird/js/main/queue.js`.

The current version of `bluebird` `2.9.34` (that should have been installed with `asyncawait`) does not have a file at that location. There is a file `bluebird/src/queue.js`, but that does not contain anything called `_makeCapacity` as is referenced in line 1 of the stack trace.

So what version of `bluebird` is installed at `/home/pi/smarthome/node_modules/asyncawait/node_modules/bluebird`?

**Comment by thekip** [comment] 2015-08-17 08:32
I have installed `2.3.11` which correctly according to package.json in asyncawait package

```js
"dependencies": {
    "bluebird": "~2.3.11",
    "fibers": "~1.0.1",
    "lodash": "v2.4.1"
  },
```

**Comment by yortus** [comment] 2015-08-17 08:47
I see. There is a `_makeCapacity` in that version of `bluebird`, and it is crashing according to your stack trace (but apparently with no error message). I'm not sure how else to help. I'm not sure why `bluebird` would crash on startup. I've never seen such an error in any other environment and I can't reproduce it.

**Comment by yortus** [comment] 2015-08-17 08:54
I see `node-fibers` is also there at the bottom of the stack trace. That is a binary module and is not compatible with all platforms and node versions. Perhaps you could try to find out whether `node-fibers` is compatible with your setup.

You could try that out by doing `npm install fibers` and then running the following sample taken directly from the `node-fibers` [README](https://github.com/laverdet/node-fibers/blob/master/README.md):

```javascript
var Fiber = require('fibers');

function sleep(ms) {
    var fiber = Fiber.current;
    setTimeout(function() {
        fiber.run();
    }, ms);
    Fiber.yield();
}

Fiber(function() {
    console.log('wait... ' + new Date);
    sleep(1000);
    console.log('ok... ' + new Date);
}).run();
console.log('back in main');
```

The expected output according to the README should be something like:
```
wait... Fri Jan 21 2011 22:42:04 GMT+0900 (JST)
back in main
ok... Fri Jan 21 2011 22:42:05 GMT+0900 (JST)
```

**Comment by thekip** [comment] 2015-08-25 07:01
I fixed it! I installed Node.js version 0.10.40 by compiling it on the Raspberry Pi itself. I used this walkthrough: http://www.armhf.com/node-js-for-the-beaglebone-black/ 

I think the problem is i have the latest Raspberry Pi which has a diffrent CPU architecture from other. 
And all binaкies from repos are incompatible.

**Comment by yortus** [comment] 2015-08-25 07:50
That's great to hear! I'll close this issue then. Happy coding.

**Closed by yortus** 2015-08-25 07:50 UTC
