### ISSUE TITLE
why so long time require this two packages?

### ISSUE THREAD

**Issue by yuchao86** [yortus/asyncawait#58] opened 2017-02-13 03:25 UTC
$ node app.js                                                                                                                          [11:20:06]
require async and await elapsed time =======>54.539ms
Express server listening on port 14082
why so long time require this two packages?

**Comment by yortus** [comment] 2018-05-07 03:17
I can't reproduce this and nobody else has commented about the issue. I think it's best to close it since its so old now. Feel free to re-open if you think this needs further investigation.

**Closed by yortus** 2018-05-07 03:17 UTC
