### ISSUE TITLE
Doesnt seem to work with ecmascript 6 class methods

### ISSUE THREAD

**Issue by sidman1988** [yortus/asyncawait#33] opened 2016-02-13 03:03 UTC
I am trying to make this work using the new classes and class method syntax in ecmascript 6, but it doesnt seem to work at all, the methods just never returns anything. Does this not yet support ecmascript 6 classes or is there a way I can make this work?

**Comment by yortus** [comment] 2016-02-13 07:43
Hi @sidman1988, can you provide an example or short repro of what you are trying to do?

**Comment by yortus** [comment] 2016-02-24 05:19
Hi @sidman1988, this really needs more information to be actionable. I'm closing it for now pending more information. Please feel free to reopen if/when you can post a sample demonstrating what you are trying to do and where the problem is occuring.

**Closed by yortus** 2016-02-24 05:19 UTC

**Comment by Wapweb** [comment] 2016-03-24 21:10
it works. here is an example
```javascript
    //active-record.js
    //....
    static count(options) {
        options = options || {};
        options.columns = ['COUNT(*) as __cnt'];

        return async(() => {
            try {
                let connection = await(getConnection());
                let query = buildSelectQuery.apply(this, [null, options]);
                let result = await(executeQuery(connection, query.query, query.bindParams));

                return result[0]['__cnt'];
            } catch (e) {
                return e;
            }
        })();
    }

   //....
   //index.js
   UserModel.count().then(result => console.log(result)).catch(error => console.log(error));
```
